baseURL: http://something-fresh.org/
languageCode: en-us
title: Antigua Tech Syndicate
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/syndicate-logo.png
    link: /   
    # Default width/height. Uncomment if you need to change
    width: 112
    height: 28
  font:
    name: "Open Sans"
    sizes: [600,600]
  hero:
    # Main hero title
    title: Welcome to the Antiguan Syndicate 
    # Hero subtitle (optional)
    subtitle: The Antigua Tech Syndicate is an association dedicated to the economic development of Antigua and its surrounding islands. We promote research, education and national prosparity through collaboration in order to foster sustainable economic growth.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: /#section1
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - marmaj
    - rcs
    - fotcp

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About Us
    url: /about
  - title: Our Top Associates
    url: /members
  - title: Activities
    sublinks:
    - title: Association Work
      url: /activities/#Association Work
    - title: Special Job Oppertunities
      url: /activities/#Special Job Oppertunities
    - title: Charity work
      url: /activities/#Charity work
  - title: Join Us
    url: /action
  - title: Socials
    url: /#footer
    button: true
  section1:
    title: The 5 Pillars of The Syndicate.
    subtitle: Five main branches, from technology to economics all perfectly organized.
    tiles:
    - title: TSRI
      icon: technology-machinery
      text: Technologies, Systems, Research, and Innovation
      url: /
      buttonText: Get started
    - title: AMEL
      icon: government-building
      text: Administration, Management, Economics, and legality
      url: /
      buttonText: Get started
    - title: BERN
      icon: bulb-on
      text: Business, Entrepreneurship, Research, negotiations
      url: /
      buttonText: Get started
    - title: ACCEL
      icon: education-learning
      text: Advocacy, Charity, Culture, Event, Learning
      url: /
      buttonText: Get started
    - title: FIAT
      icon: finance-markting
      text: Finance, Advisory, Audits, and Tracking
      url: /
      buttonText: Get started
  section2:
    title: What We Offer
    subtitle: In Our Endevor To Take The Advancement Of Our Country Into Our Own Hands.
    features:
    - title: Partnership Opportunities
      text: 
      icon: laptop-globe
    - title: Entrepreneurial Resources
      text: For more entrepreneurial-minded folks you will be able to access syndicate data and resources to use at your disposal for the execution of your idea.
      icon: doc-sync
    - title: Make a Difference in Antigua
      text: You will be able to engage in activities that directly improve the nation of Antigua and Barbuda from nonprofit ventures or provide value for customers in Antigua willing to pay
      icon: mobile-feed
  section3:
    title: Join Us
    subtitle: In Our Endevor To Take The Advancement Of Our Country Into Our Own Hands.
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Partners and Associates!
    subtitle: We are partnered with over 10 for profit and non profit organizations wo share the same vision that we do so we can help make Antigua better tomorrow than it was yesterday.
    clients:
    - name: Restore a Sense of I Can (RSC)
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      Company type: Non Profit
      Status: Associate
      img: 1
    - name: Principals Of Wealth (POW)
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Marma J Foundation 
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: mouse-globe.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - icon: facebook
    - link: https://www.facebook.com/techsyndicate.anu?mibextid=ZbWKwL
    bulmalogo: true
    quicklinks:
      column1:
        title: "Research Department"
        links:
        - text: Research Archive
          link: /
        - text: Why choose our product?
          link: /
        - text: Research Submission 
          link: /
        - text: UWI Five Islands Antigua
          link: /
        - text: Antigua State College
          link: /agb
      column2:
        title: "More Details"
        links:
        - text: Get started
          link: /
        - text: Latest Events
          link: /
        - text: Syndicate Roadmap
          link: /
        - text: Missions Board
          link: /
      column3:
        title: "Content"
        links:
        - text: Latest Blog Posts
          link: /blog/first
        - text: Newsletter
          link: /blog/second