baseURL: http://something-fresh.org/
languageCode: en-us
title: Antigua Syndicate
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/syndicate-logo.png
    link: /   
    # Default width/height. Uncomment if you need to change
    width: 112
    height: 28
  font:
    name: "Open Sans"
    sizes: [600,600]
  hero:
    # Main hero title
    title: Welcome to the Antiguan Syndicate 
    # Hero subtitle (optional)
    subtitle: Antiguan Syndicate is a unique association that uses technology to benefit Antigua and its members by providing unique opportunities.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: /#section1
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - marmaj
    - rcs
    - fotcp

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Our Story
    url: /about
  - title: See Our Members
    url: /members
  - title: Activities
    sublinks:
    - title: Association Work
      url: /activities/#Association Work
    - title: Special Job Oppertunities
      url: /activities/#Special Job Oppertunities
    - title: Charity work
      url: /activities/#Charity work
  - title: Join Us
    url: /action
  - title: Socials
    url: /
    button: true
  section1:
    title: Fields we want to expand on and explore in the country alongside our partners.
    subtitle: Five industries of intresets.
    tiles:
    - title: Technology
      icon: technology-machinery
      text: Technologies, Systems, Research, and Innovations
      url: /
      buttonText: Get started
    - title: Government
      icon: government-building
      text: Administration, Management, Economics, and legality
      url: /
      buttonText: Get started
    - title: Entrepreneurship
      icon: bulb-on
      text: Business, Entrepreneurship, Research, negotiations
      url: /
      buttonText: Get started
    - title: NGO & Education
      icon: education-learning
      text: Advocacy, Charity, Culture, Event, Learning
      url: /
      buttonText: Get started
    - title: Finance 
      icon: finance-markting
      text: Finance, Advisory, Audits, and Tracking
      url: /
      buttonText: Get started
  section2:
    title: Join Our Community of Investors and Grow Your Wealth Together
    subtitle: Become a Member, Associate, or Investor Today and Start Reaping the Benefits.
    features:
    - title: Partnership Opportunities
      text: We are partnered with over 6 highly influential companies with external connections so we can provide jobs to members and many more will be on the way as we expand
      icon: laptop-globe
    - title: Entrepreneurial Resources
      text: For more entrepreneurial-minded folks you will be able to access syndicate data and resources to use at your disposal for the execution of your idea.
      icon: doc-sync
    - title: Make a Difference in Antigua
      text: You will be able to engage in activities that directly improve the nation of Antigua and Barbuda from nonprofit ventures or provide value for customers in Antigua willing to pay
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second