baseURL: http://something-fresh.org/
languageCode: en-us
title: Antigua Tech Syndicate
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/syndicate-logo.png
    link: /   
    # Default width/height. Uncomment if you need to change
    width: 112
    height: 28
  font:
    name: "Open Sans"
    sizes: [600,600]
  hero:
    # Main hero title
    title: Welcome to the Antiguan Syndicate 
    # Hero subtitle (optional)
    subtitle: The Antigua Tech Syndicate is an association dedicated to the economic development of Antigua and its surrounding islands. We promote research, education and national prosparity through collaboration in order to foster sustainable economic growth.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: /#section1
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - marmaj
    - rcs
    - fotcp

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About Us
    url: /about
  - title: Our Top Associates
    url: /members
  - title: Activities
    sublinks:
    - title: Association Work
      url: /activities/#Association Work
    - title: Special Job Oppertunities
      url: /activities/#Special Job Oppertunities
    - title: Charity work
      url: /activities/#Charity work
  - title: Join Us
    url: /action
  - title: Socials
    url: /#footer
    button: true
  section1:
    title: The 5 Pillars of The Syndicate.
    subtitle: Five main branches, from technology to economics all perfectly organized.
    tiles:
    - title: TSRI
      icon: technology-machinery
      text: Technologies, Systems, Research, and Innovation
      url: /
      buttonText: Get started
    - title: AMEL
      icon: government-building
      text: Administration, Management, Economics, and legality
      url: /
      buttonText: Get started
    - title: BERN
      icon: bulb-on
      text: Business, Entrepreneurship, Research, negotiations
      url: /
      buttonText: Get started
    - title: ACCEL
      icon: education-learning
      text: Advocacy, Charity, Culture, Event, Learning
      url: /
      buttonText: Get started
    - title: FIAT
      icon: finance-markting
      text: Finance, Advisory, Audits, and Tracking
      url: /
      buttonText: Get started
  section2:
    title: Our Mission & Vision
    subtitle: Our Goals, Aspiratons and Ideals.
    features:
    - title: Provisions  
      text: We aim to provide research, education, and collaboration opportunities to drive sustainable economic growth.
      icon: laptop-globe
    - title: Opportunity 
      text: We will maintain a vibrant, equitable, and sustainable organisation in order To foster an environment of opportunity and inclusive growth.
      icon: doc-sync
    - title: Promise
      text: We ensure that with your assistance we will continue to do our absolute best to create change that will benefit the people of Antigua and Barbuda.
      icon: mobile-feed
  section3:
    title: Join Us
    subtitle: In Our Endevor To Take The Advancement Of Our Country Into Our Own Hands.
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Partners and Associates!
    subtitle: We are partnered with over 10 for profit and non profit organizations wo share the same vision that we do so we can help make Antigua better tomorrow than it was yesterday.
    clients:
    - name: (RSC)
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Restore A Sense Of I Can
      img: 1
    - name: (POW)
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Principals Of Wealth 
      img: 2
    - name: Marma J Foundation 
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: 
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://www.facebook.com/techsyndicate.anu?mibextid=ZbWKwL
      icon: facebook
    bulmalogo: true
    quicklinks:
      column1:
        title: "Research Dep"
        links:
        - text: Research Archive
          link: /
        - text: Why choose our product?
          link: /
        - text: Research Submission 
          link: /
        - text: UWI Five Islands Antigua
          link: /
        - text: Antigua State College
          link: /agb
      column2:
        title: "More Details"
        links:
        - text: Get started
          link: /
        - text: Latest Events
          link: /
        - text: Syndicate Roadmap
          link: /
        - text: Missions Board
          link: /
        - text: Current Progress
          link: /
      column3:
        title: "Content"
        links:
        - text: Latest Blog Posts
          link: /blog/first
        - text: Newsletter
          link: /blog/second